# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncp < Formula
  desc "NCP is a file transfer utility that enables efficient copying of files to and from an NFS server."
  homepage "https://ncp.lmno.pk"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Darwin_x86_64.tar.gz"
      sha256 "cf57b1ac0331b357a2c951e14377067f5b3c7b04e39eb439f8b92601820c59d2"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Darwin_arm64.tar.gz"
      sha256 "10e7cd2b4cb1cb76d4511a1317c89bc34d05636726bd6f50406e61e36ea458b7"

      def install
        bin.install "ncp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Linux_arm64.tar.gz"
      sha256 "035b7b12b3cdd0ff71c32348b4072a44dd59d90c1f7b1118a791d8b8b9c047f6"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Linux_x86_64.tar.gz"
      sha256 "f03a056274f50e5d8c296c010570de4395c207aa69c39bf1957a65e0d9f375f4"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Linux_arm.tar.gz"
      sha256 "f37cb5e0c6c74485f8978be3ea0f92189deeaa5ec9b64f6c074364ddecdebc5d"

      def install
        bin.install "ncp"
      end
    end
  end

  test do
    system "#{bin}/ncp -v"
  end
end
