# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncp < Formula
  desc "NCP is a file transfer utility that enables efficient copying of files to and from an NFS server."
  homepage "https://ncp.lmno.pk"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.3/ncp_Darwin_arm64.tar.gz"
      sha256 "ff41bfcb2ec9318820495f9850753aaf481300fa529807073df15d86bff41aef"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.3/ncp_Darwin_x86_64.tar.gz"
      sha256 "864058185115c530397bc29fec7be8c56438917fd22dd66ea20b62ef0ea55b21"

      def install
        bin.install "ncp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.3/ncp_Linux_arm64.tar.gz"
      sha256 "688ceabcbd21b52405d0c0d888b8eceb36e4615c99b02661ad98c4e3964a6cad"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.3/ncp_Linux_x86_64.tar.gz"
      sha256 "66b2352df1567d366ffe7fed92aef4c949a0189f289701e81c9e46dff633504d"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.3/ncp_Linux_arm.tar.gz"
      sha256 "01a83c66558dacb256fecf5662c7c30ac3b3753ab89c74540119f353b5773bd1"

      def install
        bin.install "ncp"
      end
    end
  end

  test do
    system "#{bin}/ncp -v"
  end
end
