# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncp < Formula
  desc "NCP is a file transfer utility that enables efficient copying of files to and from an NFS server."
  homepage "https://ncp.lmno.pk"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Darwin_arm64.tar.gz"
      sha256 "a1bb573795f9dcc774dbdcda6c3e025fb33315d5c4834999af07161bb67f3f03"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Darwin_x86_64.tar.gz"
      sha256 "a0e50b980e13c70bc69f151db04d5044ad6bb332f1462d9e3a3b541d5b2cf21f"

      def install
        bin.install "ncp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Linux_arm.tar.gz"
      sha256 "835fd85309c16985d4b13fdbb842db548e00ecddee92522f6c6a1a31d7254135"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Linux_arm64.tar.gz"
      sha256 "8e4c0bc7a7f65ce7ca9e3612a66cdfb208f7290e6bf4dcc35ae541e27e42e49d"

      def install
        bin.install "ncp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/ncp/releases/download/v0.1.1/ncp_Linux_x86_64.tar.gz"
      sha256 "db89c545fc82c493bfd154c489a30835cfa8da04008e35f42bfd6ed05e346ffd"

      def install
        bin.install "ncp"
      end
    end
  end

  test do
    system "#{bin}/ncp -v"
  end
end
