# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingme < Formula
  desc "PingMe is a CLI tool which provides the ability to send messages or alerts to multiple messaging platforms."
  homepage "pingme.lmno.pk"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.0/pingme_Darwin_x86_64.tar.gz"
      sha256 "bb30204a44d07bc9ffae621714b32458d02b8bfb4cb598c7aa1ae70447de66d2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.0/pingme_Darwin_arm64.tar.gz"
      sha256 "a85ef42f9e5c489914645307f04e41295803cf7f7ccb3a63d48d94dba8195419"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.0/pingme_Linux_x86_64.tar.gz"
      sha256 "6cb4fc5d7a8a56043eb81d0d38bed8a7341505b18e5e831d9ad779e95958b439"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.0/pingme_Linux_armv6.tar.gz"
      sha256 "bd5d7d9e0c93333bfd38f3a580d2bcd71fa10f734a4cc51d50658e1b7670ec78"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.0/pingme_Linux_arm64.tar.gz"
      sha256 "cb30e8fef2cd12e60a3b764bbb62607e7eea72ee0a5a843e42f36142016e67e3"
    end
  end

  def install
    bin.install "pingme"
  end

  test do
    system "#{bin}/pingme -v"
  end
end
