# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingme < Formula
  desc "PingMe is a CLI tool which provides the ability to send messages or alerts to multiple messaging platforms."
  homepage "pingme.lmno.pk"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.4/pingme_Darwin_x86_64.tar.gz"
      sha256 "567a13ecb2461bcb64a861d8ccc852b2b07905f2ec22a6c7e2dc5cc27065de5b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.4/pingme_Darwin_arm64.tar.gz"
      sha256 "76958f42e8f6ed301413bf64fa61eb77e727d13d49eca34e771fe8527daaf235"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.4/pingme_Linux_x86_64.tar.gz"
      sha256 "f50558f8b442b319b306dc1ee4619293ac4d0ace5cadba8fd6f129ea100ea6ca"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.4/pingme_Linux_armv6.tar.gz"
      sha256 "dce55cab68cbb9f727b5aaa5f64fc08f1132f5e126a3a578260fc1a75609c32d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/pingme/releases/download/v0.2.4/pingme_Linux_arm64.tar.gz"
      sha256 "92ac1ef472fe7b140309dc426e49d34b4a69e72c5c1c66764c23d78943c34798"
    end
  end

  def install
    bin.install "pingme"
  end

  test do
    system "#{bin}/pingme -v"
  end
end
