# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subvars < Formula
  desc "Substitute environment variables from command line in config files defined as go template format."
  homepage "subvars.lmno.pk"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kha7iq/subvars/releases/download/v0.1.5/subvars_Darwin_arm64.tar.gz"
      sha256 "786e04d24a2683eae9d3972a8f3cd6fd76739419a2aa704b361cf8031ba90ce9"

      def install
        bin.install "subvars"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/subvars/releases/download/v0.1.5/subvars_Darwin_x86_64.tar.gz"
      sha256 "88661413a0de67c06b9e4a55de44b127bc604185c566770d4314f9dab76d0fca"

      def install
        bin.install "subvars"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kha7iq/subvars/releases/download/v0.1.5/subvars_Linux_x86_64.tar.gz"
      sha256 "2426c7ac07831bdf8d410ee9d6cea73db447b0314842dbb7c0c80a0a425af86c"

      def install
        bin.install "subvars"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/subvars/releases/download/v0.1.5/subvars_Linux_arm.tar.gz"
      sha256 "cef0fefeece9f7cfb1ed7b2ad51ff6c47cfd56df60d6ae40eecda83fb27e09e5"

      def install
        bin.install "subvars"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kha7iq/subvars/releases/download/v0.1.5/subvars_Linux_arm64.tar.gz"
      sha256 "80385062c52c45a7b5905adde7abb070c0b9d835638d2667a4142781e02f9250"

      def install
        bin.install "subvars"
      end
    end
  end

  test do
    system "#{bin}/subvars -v"
  end
end
